export let example_properties = {
    Pitch: {
      transformDocUUID: "1234",
      backendAPIType: "Pitch",
      callbackURL: "https://www.google.com",
      transformKey: "Pitch",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    ImpactStatement: {
      transformDocUUID: "1234",
      backendAPIType: "ImpactStatement",
      callbackURL: "https://www.google.com",
      transformKey: "ImpactStatement",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    SolutionStatement: {
      transformDocUUID: "1234",
      backendAPIType: "SolutionStatement",
      callbackURL: "https://www.google.com",
      transformKey: "SolutionStatement",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    ProblemStatement: {
      transformDocUUID: "1234",
      backendAPIType: "ProblemStatement",
      callbackURL: "https://www.google.com",
      transformKey: "ProblemStatement",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    BusinessCaseStatement: {
      transformDocUUID: "1234",
      backendAPIType: "BusinessCaseStatement",
      callbackURL: "https://www.google.com",
      transformKey: "BusinessCaseStatement",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    "StoryInfuserTechnical Insights": {
      transformDocUUID: "1234",
      backendAPIType: "StoryInfuserTechnicalInsights",
      callbackURL: "https://www.google.com",
      transformKey: "StoryInfuserTechnical Insights",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    StoryInfuserPatientStory: {
      transformDocUUID: "1234",
      backendAPIType: "StoryInfuserPatientStory",
      callbackURL: "https://www.google.com",
      transformKey: "StoryInfuserPatientStory",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    StoryInfuserChallengeStory: {
      transformDocUUID: "1234",
      backendAPIType: "StoryInfuserChallengeStory",
      callbackURL: "https://www.google.com",
      transformKey: "StoryInfuserChallengeStory",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    InnoStoryFailureStory: {
      transformDocUUID: "1234",
      backendAPIType: "InnoStoryFailureStory",
      callbackURL: "https://www.google.com",
      transformKey: "InnoStoryFailureStory",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
    },
    BLUF: {
      transformDocUUID: "1234",
      backendAPIType: "transform BLUF",
      callbackURL: "https://www.google.com",
      transformKey: "BLUF",
      uploadedContent: "This is the content that was uploaded",
    },
    Summarize: {
      transformDocUUID: "1234",
      backendAPIType: "transform Summarize",
      callbackURL: "https://www.google.com",
      transformKey: "Summarize",
      uploadedContent: "This is the content that was uploaded",
    },
    Simplify: {
      transformDocUUID: "1234",
      backendAPIType: "transform Simplify",
      callbackURL: "https://www.google.com",
      transformKey: "Simplify",
      uploadedContent: "This is the content that was uploaded",
    },
    ValueProposition: {
      transformDocUUID: "1234",
      backendAPIType: "transform ValueProposition",
      callbackURL: "https://www.google.com",
      transformKey: "ValueProposition",
      uploadedContent: "This is the content that was uploaded",
    },
    WhitePaper: {
      transformDocUUID: "1234",
      backendAPIType: "WhitePaper",
      transformKey: "WhitePaper",
      callbackURL: "https://www.google.com",
      questions: ["q_one", "q_two", "q_three", "q_four", "q_five", "q_six", "q_seven", "q_eight", "q_nine", "q_ten", "q_1one", "q_1two", "q_1three", "q_1four", "q_1five", "q_1six", "q_1seven", "q_1eight"],
      answers: ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "1one", "1two", "1three", "1four", "1five", "1six", "1seven", "1eight"],
    },
    ArticleFromScratch: {
      transformDocUUID: "1234",
      backendAPIType: "ArticleFromScratch",
      callbackURL: "https://www.google.com",
      transformKey: "ArticleFromScratch",
      questions: ["What is the problem?", "What is the solution?", "What is the impact?"],
      answers: ["The problem is that there is no solution", "The solution is to create a solution", "The impact is that there is no impact"],
      uploadedContent: "This is the content that was uploaded"
    },
    CaseStudy: {
      transformDocUUID: "1234",
      backendAPIType: "CaseStudy",
      callbackURL: "https://www.google.com",
      transformKey: "CaseStudy",
      answers: ["one", "two", "three", "four", "five"],
    },
    "WFF-TRC Concept Note": {
      transformDocUUID: "1234",
      backendAPIType: "WFF-TRC Concept Note",
      callbackURL: "https://www.google.com",
      transformKey: "WFF-TRC Concept Note",
      answers: ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"],
    },
  };